isomerpages/moe-junyuanpri

index.md
=> Update on the homepage to remove the Contact Us

_config.yml, index.md
For your approval in correcting the site name from Junyan Primary School to Junyuan Primary School. Thanks
=> Correction of Site name 

_data/navigation.yml, _jyps-kids-cafe/JYPS Kids Cafe.md
For your approval to redirect Kids Cafe to https://jyps-kids-cafe.learn-at-jyps.sg/ directly when click. Thanks
=> Updates for JYPS Kids Cafe

_mk-at-junyuan/Staff List.md, index.md
For your approval on the following changes:
1) update to MK staff list
2) removal of school bus advertisement from Homepage's Announcement section.
Thank you.
=> Updates to website content

_jyps-family/Our Staff/EAS & Support Staff.md, index.md
Dear Evelyn, for your approval on the following changes:
1) Removal of Emerson from EAS & Support Staff list
2) Change of Announcement to JYPS September Bulletin
Thanks
=> Updates to School Website

_parents-portal/Road Safety of Students.md
Dear Evelyn, 
for your approval on the updates on the resource links for 'Road Safety of Students' webpage.
Thanks
=> Updates to the resource links

_jyps-family/Our Staff/EAS & Support Staff.md
Dear Evelyn, 
for your approval on the changes in staff movement
1) New addition of ICTM
2) change in Security Guard
Thanks
=> Changes in Staff Movement

_parents-portal/Downloads & Links.md, _parents-portal/Transition to Secondary School/My Secondary School Education Journey.md
Dear Evelyn,
For your approval on the following changes:
1) update the link to the P1 microsite
2) Update to the transition to Secondary school webpage;
Thanks
=> Updates to the school websites

_jyps-family/Our Staff/Non Form Teachers.md, _jyps-family/Our Staff/Teacher Leaders.md
Dear Evelyn, for your approval on the following:
1) changes in Teacher Leaders Page
2) changes in Non-Form Teachers Page.
Thanks
=> Jan2024 - Changes to JYPS Family

_jyps-family/Our Staff/Primary 1 Teachers.md, _mk-at-junyuan/MK Registration.md
Dear Evelyn,
For your approval on the following changes:
1) Rectify the MK waitlist link
2) Update staff name (Nadhira)
Thank you.
=> Feb2024: Changes to School Website

_jyps-family/Our Staff/Primary 5 Teachers.md, _jyps-family/Our Staff/Primary 6 Teachers.md, _mk-at-junyuan/MK Registration.md
Dear Evelyn, 
For your approval to the changes to 
1) MK Registration webpage. 
2) Changes to P5 and P6 FT webpages
Thanks
=> Apr2024: Changes to school website

_parents-portal/JYPS Bulletin.md, index.md
Dear Evelyn,
For your approval in the bulletin name from May/June to May-June
Thanks
=> Apr2024: Changes to Bulletin Name

_jyps-family/Our Staff/Allied Educators (AED).md, _parents-portal/Downloads & Links.md, index.md
Dear Evelyn,
For your approval in the following changes:
1) Staff Movement - Removal of Win Lin 
2) Update to the homepage to remove the announcement for ECHA nomination and Alumni coming back to school on 29Aug.
Thanks
=> Sep2024: Updates to School Website

_parents-portal/Downloads & Links.md
Dear Evelyn,
For your approval to upload 2025 booklists under Download and Links page.
Thanks
=> Nov2024: Updates to School Website

_jyps-family/Our Staff/Primary 4 Teachers.md
Dear Evelyn, for your approval to update the classing for P4 classes. Thanks
=> Update to school website

_cce/Sexuality Education Programme (SEd).md
Dear Evelyn / Celia,
Please help to approve 
1) updated sentence in CCE Sed page.
Thanks.
=> Jan2025: Updates to School Website

_cce/Sexuality Education Programme (SEd).md
Dear Evelyn & Celia,
For your approval to the changes in CCE SEd.
Thanks
=> Apr2025: Updates to CCE SEd

_cce/Sexuality Education Programme (SEd).md
Dear Evelyn / Celia,
For your approval in the changes to the CCE SEd wording.
Thanks
=> Apr2025: Changes to CCE SEd wording

_cce/Sexuality Education Programme (SEd).md, _parents-portal/Cyber Wellness.md
Dear Evelyn / Celia,
For your approval in the following changes:
1) Removal of New and 2023 from header "Resources"
2) Removal of extra punctuation full stops.
Thanks
=> Apr2025: Updates to Cyberwellness and CCE SEd

_departments/Mathematics.md, _jyps-family/Our Staff/SEN Officers.md, _jyps-family/Our Staff/Steering Committee.md, _jyps-family/Our Staff/Teacher Leaders.md, _parents-portal/Methodist Welfare Services Family Support Programme.md, _parents-portal/collection.yml
Der Evelyn & Celia,
For your approval on the following changes:
1) Removal of Methodist Welfare Services Family Support Programme webpage
2) Update of staff movement (change in designations) 
3) Update for Math dept to include student achievements for AY 2024
Thanks
=> Jul2025: Updates to School Website

_cce/ECHA.md, _jyps-family/Our Staff/EAS & Support Staff.md, index.md
Dear Evelyn & Celia,
For your approval in the following changes:
1) Staff movement for EAS & Support team
2) Update of JYPS ECHA 
Thanks
=> July2025: Updates to School Website

_jyps-family/Our Staff/EAS & Support Staff.md
Dear Evelyn & Celia,
For your approval on the staff movement - removal of Juhanis from EAS & Support Staff Webpage
Thanks
=> Sep2025: Update to school website

_jyps-family/Our Staff/EAS & Support Staff.md
Dear Evelyn & Celia,
For your approval in staff movement for EAS & Support Team.
Thank you.
=> Oct2025: Updates to the school website
